In [ ]:
import requests
import os
import time
import random
import json
import pandas as pd
from bs4 import BeautifulSoup

# Load data
df = pd.read_excel(r"D:\Nexensus_Projects\Incorporation\input_folder\Shivam Sir incorporation.xlsx")[:5]

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    "Accept-Language": "en-US,en;q=0.9",
    "Referer": "https://www.tofler.in/"
}

output_file = "output.txt"

with open(output_file, "w", encoding="utf-8") as f:
    for row in df.itertuples(index=False):
        cin = row.cin
        input_name = row.name  
        url = f"https://www.tofler.in/company/{cin}"

        try:
            response = requests.get(url, headers=headers, timeout=60)
            soup = BeautifulSoup(response.text, 'html.parser')

            tag = soup.find(class_="accordion_content p-20 rounded-md")
            incorporation = tag.text.strip() if tag else None

            # Create JSON line
            record = {
                "name": input_name,
                "cin": cin,
                "incorporation": incorporation
            }

            # Write as JSON line
            f.write(json.dumps(record, ensure_ascii=False) + "\n")

            print(f"✅ Done: {cin}")

        except Exception as e:
            print(f"❌ Error for {cin}: {e}")

        time.sleep(random.uniform(2, 4))  # polite delay

The incorporation date of VAARI DAIRY PRIVATE LIMITED is 23 September, 2025


The incorporation date of BANARASIYA FOODS AND BEVERAGES PRIVATE LIMITED is 21 April, 2025


The incorporation date of KRSD TECHNOLOGY PRIVATE LIMITED is 30 May, 2025


The incorporation date of XPLOR COMMUNITY SOLUTIONS PRIVATE LIMITED is 07 April, 2023


The incorporation date of SCRAPON WHEELS GLOBAL PRIVATE LIMITED is 07 April, 2022


The incorporation date of PROWPLUS AI PRIVATE LIMITED is 07 November, 2025


The incorporation date of INSOFT INTERNATIONAL PRODUCTS PRIVATE LI MITED is 05 May, 2003

'\nThe incorporation date of KRSD TECHNOLOGY PRIVATE LIMITED is 30 May, 2025\n'

In [ ]:
####################### Code to combine all csv files downloaded for all states ######################
import pandas as pd
import os

# 🔹 Input and Output paths
input_folder = r"D:\Nexensus_Projects\Incorporation\output_folder\downloaded_company_csv"   # change this
output_file = r"merged.csv"

# 🔹 Get all CSV files
csv_files = [f for f in os.listdir(input_folder) if f.endswith(".csv")]

# 🔹 List to store dataframes
df_list = []

for file in csv_files:
    file_path = os.path.join(input_folder, file)
    try:
        df = pd.read_csv(file_path)
        df["source_file"] = file   # optional: track source
        df_list.append(df)
        print(f"✅ Loaded: {file}")
    except Exception as e:
        print(f"❌ Skipped: {file} | Error: {e}")

# 🔹 Merge all dataframes
if df_list:
    merged_df = pd.concat(df_list, ignore_index=True)

    # 🔹 Save to CSV
    merged_df = pd.concat(df_list, ignore_index=True, sort=False)
    print(f"\n🎉 Merged file saved at: {output_file}")
else:
    print("⚠️ No valid CSV files found.")

merged_df.drop_duplicates().to_csv("master.csv")

✅ Loaded: 4dbe5667-7b6b-41d7-82af-211562424d9a_1252bebd7fbf8ab28224e1de1e4582e8.csv
✅ Loaded: 4dbe5667-7b6b-41d7-82af-211562424d9a_169c8840480f2cab05deb83a9aceaba3.csv
✅ Loaded: 4dbe5667-7b6b-41d7-82af-211562424d9a_1bbd2f6da617b1b3b16cafa28383a029.csv

C:\Users\PC\AppData\Local\Temp\ipykernel_22896\2287672419.py:17: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

✅ Loaded: 4dbe5667-7b6b-41d7-82af-211562424d9a_1e5c6d80580310d08ab5e80c84dfb7bf.csv
✅ Loaded: 4dbe5667-7b6b-41d7-82af-211562424d9a_224373a235b159e4393a14d889945b8e.csv
✅ Loaded: 4dbe5667-7b6b-41d7-82af-211562424d9a_2d362bf20d1b31b0d52e155e700ec613.csv
✅ Loaded: 4dbe5667-7b6b-41d7-82af-211562424d9a_30948aedacec2d7d0b80ad794ed969c3.csv
✅ Loaded: 4dbe5667-7b6b-41d7-82af-211562424d9a_363c40a80f2d1221d016bc62e88fbb52.csv

C:\Users\PC\AppData\Local\Temp\ipykernel_22896\2287672419.py:17: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

✅ Loaded: 4dbe5667-7b6b-41d7-82af-211562424d9a_3a23d1349c6682894f0ced239e3d91bb.csv

C:\Users\PC\AppData\Local\Temp\ipykernel_22896\2287672419.py:17: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

✅ Loaded: 4dbe5667-7b6b-41d7-82af-211562424d9a_3c951b1b23d1c74aecf246905893f242.csv
✅ Loaded: 4dbe5667-7b6b-41d7-82af-211562424d9a_41c5781a8bd274c68d87499cd96d3260.csv
✅ Loaded: 4dbe5667-7b6b-41d7-82af-211562424d9a_44477ca2acd5d9e1eb884df91f05f4e1.csv

C:\Users\PC\AppData\Local\Temp\ipykernel_22896\2287672419.py:17: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

✅ Loaded: 4dbe5667-7b6b-41d7-82af-211562424d9a_45b2b430e969c5df4004f8e745b49f49.csv
✅ Loaded: 4dbe5667-7b6b-41d7-82af-211562424d9a_47aea10fb5589393304693a65f06cf2c.csv
✅ Loaded: 4dbe5667-7b6b-41d7-82af-211562424d9a_598f0c4a45b00d90466b5b4c76d9cdae.csv
✅ Loaded: 4dbe5667-7b6b-41d7-82af-211562424d9a_5e53a42d3afab3295fb0d7074ccd0871.csv

C:\Users\PC\AppData\Local\Temp\ipykernel_22896\2287672419.py:17: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

✅ Loaded: 4dbe5667-7b6b-41d7-82af-211562424d9a_625e1550a77538ff9e0fe943074cb313.csv
✅ Loaded: 4dbe5667-7b6b-41d7-82af-211562424d9a_664e34f86c6a4be35a079b505d89a4b8.csv
✅ Loaded: 4dbe5667-7b6b-41d7-82af-211562424d9a_7235c55ef3b2683ab9a852267cd5e915.csv
✅ Loaded: 4dbe5667-7b6b-41d7-82af-211562424d9a_74c312f3fe8611deae17aba87864ab8d.csv
✅ Loaded: 4dbe5667-7b6b-41d7-82af-211562424d9a_7d49cf88f17d4d5e5a5e2ed3ce0aa562.csv
✅ Loaded: 4dbe5667-7b6b-41d7-82af-211562424d9a_938c98054cc1d7accea56d9e2b6a31cb.csv
✅ Loaded: 4dbe5667-7b6b-41d7-82af-211562424d9a_967c16b3523cef789b591367751d89db.csv
✅ Loaded: 4dbe5667-7b6b-41d7-82af-211562424d9a_9e0cf19e50d0eb605f3d03fb0b443970.csv

C:\Users\PC\AppData\Local\Temp\ipykernel_22896\2287672419.py:17: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

✅ Loaded: 4dbe5667-7b6b-41d7-82af-211562424d9a_9ea59325573ad17fc2f9046a30dacbe4.csv
✅ Loaded: 4dbe5667-7b6b-41d7-82af-211562424d9a_b2117942def448faf52c4546eba39fe5.csv
✅ Loaded: 4dbe5667-7b6b-41d7-82af-211562424d9a_b65714187169054903db7b04330fa089.csv
✅ Loaded: 4dbe5667-7b6b-41d7-82af-211562424d9a_c1ac42e3038e07863ad96fbc7967b173.csv

C:\Users\PC\AppData\Local\Temp\ipykernel_22896\2287672419.py:17: DtypeWarning: Columns (7,14) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

✅ Loaded: 4dbe5667-7b6b-41d7-82af-211562424d9a_cc3dfc4818f369b10eb9b491df533b8b.csv
✅ Loaded: 4dbe5667-7b6b-41d7-82af-211562424d9a_d2f7218da9ebe9fa9cec00017833e6b6.csv
✅ Loaded: 4dbe5667-7b6b-41d7-82af-211562424d9a_d6760db7b54529f88b50cdcce0600679.csv
✅ Loaded: 4dbe5667-7b6b-41d7-82af-211562424d9a_d68f6d2cbd0b5c0f504c9f546256435e.csv
✅ Loaded: 4dbe5667-7b6b-41d7-82af-211562424d9a_da87a5b2f48c99fa42a63666af691a40.csv

C:\Users\PC\AppData\Local\Temp\ipykernel_22896\2287672419.py:17: DtypeWarning: Columns (7,14) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

✅ Loaded: 4dbe5667-7b6b-41d7-82af-211562424d9a_dff39c000aa72a24e9277a4913efcc74.csv
✅ Loaded: 4dbe5667-7b6b-41d7-82af-211562424d9a_ee00234ebaf774c016aa74bd86736693.csv

C:\Users\PC\AppData\Local\Temp\ipykernel_22896\2287672419.py:17: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

✅ Loaded: 4dbe5667-7b6b-41d7-82af-211562424d9a_eef3fb3e2ad199156359edb2cf08fe31.csv
✅ Loaded: 4dbe5667-7b6b-41d7-82af-211562424d9a_f86d1f86951c4dc14ca3651408fb91f2.csv

🎉 Merged file saved at: merged.csv

In [ ]:
################# Code to map incorporation date into input file using mapped master csv file #########
import pandas as pd

# 🔹 Load files
input_file = r"D:\Nexensus_Projects\Incorporation\input_folder\Shivam Sir incorporation.xlsx"        # file with CINs
master_file = r"D:\Nexensus_Projects\Incorporation\master.csv" # master data

df_input = pd.read_excel(input_file)
df_master = pd.read_csv(master_file)

master_dict = pd.read_csv(master_file).set_index('CIN')['CompanyRegistrationdate_date'].to_dict()

df_input['registration_date'] = df_input['CIN'].map(master_dict)

df_input.to_csv("mapped_output.csv", index=False)

C:\Users\PC\AppData\Local\Temp\ipykernel_22896\2224672882.py:8: DtypeWarning: Columns (8,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df_master = pd.read_csv(master_file)
C:\Users\PC\AppData\Local\Temp\ipykernel_22896\2224672882.py:10: DtypeWarning: Columns (8,15) have mixed types. Specify dtype option on import or set low_memory=False.
  master_dict = pd.read_csv(master_file).set_index('CIN')['CompanyRegistrationdate_date'].to_dict()

In [1]:
import pandas as pd

        # file with CINs
master_file = r"D:\Nexensus_Projects\Incorporation\master.csv" # master data

df_master = pd.read_csv(master_file)

C:\Users\PC\AppData\Local\Temp\ipykernel_6528\3689776102.py:6: DtypeWarning: Columns (8,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df_master = pd.read_csv(master_file)

In [12]:
df_master.head()

,Unnamed: 0,CIN,CompanyName,CompanyROCcode,CompanyCategory,CompanySubCategory,CompanyClass,AuthorizedCapital,PaidupCapital,CompanyRegistrationdate_date,Registered_Office_Address,Listingstatus,CompanyStatus,CompanyStateCode,CompanyIndian/Foreign Company,nic_code,CompanyIndustrialClassification,source_file
0,0,U25205MP2021PTC054721,PEPPE INT. PRIVATE LIMITED,ROC Gwalior,Company limited by shares,Non-government company,Private,100000.0,100000.0,2021-02-02,"10/1 Manoramaganj 101 RK Complex,Indore,Indore...",Unlisted,Strike Off,madhya pradesh,India,25205.0,"Manufacturing (Metals and Chemicals, and produ...",4dbe5667-7b6b-41d7-82af-211562424d9a_1252bebd7...
1,1,U25209MP1996PLC011112,PAS GRANITES LIMITED,ROC Gwalior,Company limited by shares,Non-government company,Public,500000.0,700.0,1996-08-13,"8/3/1,OLD-PALASIA,BEHIND NAVNEET-TOWER, INDO...",Unlisted,Strike Off,madhya pradesh,India,25209.0,"Manufacturing (Metals and Chemicals, and produ...",4dbe5667-7b6b-41d7-82af-211562424d9a_1252bebd7...
2,2,U25209MP2016PTC041629,ADINATH POLY PLAST PRIVATE LIMITED,ROC Gwalior,Company limited by shares,Non-government company,Private,1500000.0,1500000.0,2016-10-10,"364 MR-5, Mahalaxmi Nagar Nariman Point Road...",Unlisted,Active,madhya pradesh,India,25209.0,"Manufacturing (Metals and Chemicals, and produ...",4dbe5667-7b6b-41d7-82af-211562424d9a_1252bebd7...
3,3,U25209MP2019PTC050198,QASWA POLYMERS PRIVATE LIMITED,ROC Gwalior,Company limited by shares,Non-government company,Private,1500000.0,100000.0,2019-11-27,"WARD NO- 14 HADAIPUR, MPEB CAMPUS,BEGUMGANJ,...",Unlisted,Active,madhya pradesh,India,25209.0,"Manufacturing (Metals and Chemicals, and produ...",4dbe5667-7b6b-41d7-82af-211562424d9a_1252bebd7...
4,4,U25209MP2022PTC062147,SAF-DEV VENTURES PRIVATE LIMITED,ROC Gwalior,Company limited by shares,Non-government company,Private,50000000.0,100000.0,2022-08-05,"Shop No. 2-3 Ram krishna Complex,,Navlakha,,In...",Unlisted,Active,madhya pradesh,India,25209.0,"Manufacturing (Metals and Chemicals, and produ...",4dbe5667-7b6b-41d7-82af-211562424d9a_1252bebd7...

In [23]:
df_master[df_master["CompanyIndustrialClassification"] != "Others"]

,Unnamed: 0,CIN,CompanyName,CompanyROCcode,CompanyCategory,CompanySubCategory,CompanyClass,AuthorizedCapital,PaidupCapital,CompanyRegistrationdate_date,Registered_Office_Address,Listingstatus,CompanyStatus,CompanyStateCode,CompanyIndian/Foreign Company,nic_code,CompanyIndustrialClassification,source_file
0,0,U25205MP2021PTC054721,PEPPE INT. PRIVATE LIMITED,ROC Gwalior,Company limited by shares,Non-government company,Private,100000.0,100000.0,2021-02-02,"10/1 Manoramaganj 101 RK Complex,Indore,Indore...",Unlisted,Strike Off,madhya pradesh,India,25205.0,"Manufacturing (Metals and Chemicals, and produ...",4dbe5667-7b6b-41d7-82af-211562424d9a_1252bebd7...
1,1,U25209MP1996PLC011112,PAS GRANITES LIMITED,ROC Gwalior,Company limited by shares,Non-government company,Public,500000.0,700.0,1996-08-13,"8/3/1,OLD-PALASIA,BEHIND NAVNEET-TOWER, INDO...",Unlisted,Strike Off,madhya pradesh,India,25209.0,"Manufacturing (Metals and Chemicals, and produ...",4dbe5667-7b6b-41d7-82af-211562424d9a_1252bebd7...
2,2,U25209MP2016PTC041629,ADINATH POLY PLAST PRIVATE LIMITED,ROC Gwalior,Company limited by shares,Non-government company,Private,1500000.0,1500000.0,2016-10-10,"364 MR-5, Mahalaxmi Nagar Nariman Point Road...",Unlisted,Active,madhya pradesh,India,25209.0,"Manufacturing (Metals and Chemicals, and produ...",4dbe5667-7b6b-41d7-82af-211562424d9a_1252bebd7...
3,3,U25209MP2019PTC050198,QASWA POLYMERS PRIVATE LIMITED,ROC Gwalior,Company limited by shares,Non-government company,Private,1500000.0,100000.0,2019-11-27,"WARD NO- 14 HADAIPUR, MPEB CAMPUS,BEGUMGANJ,...",Unlisted,Active,madhya pradesh,India,25209.0,"Manufacturing (Metals and Chemicals, and produ...",4dbe5667-7b6b-41d7-82af-211562424d9a_1252bebd7...
4,4,U25209MP2022PTC062147,SAF-DEV VENTURES PRIVATE LIMITED,ROC Gwalior,Company limited by shares,Non-government company,Private,50000000.0,100000.0,2022-08-05,"Shop No. 2-3 Ram krishna Complex,,Navlakha,,In...",Unlisted,Active,madhya pradesh,India,25209.0,"Manufacturing (Metals and Chemicals, and produ...",4dbe5667-7b6b-41d7-82af-211562424d9a_1252bebd7...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3317877,3674311,U72300TR2013PTC008386,TRIPURA CHRONICLE PRIVATE LIMITED,ROC Guwahati,Company limited by guarantee,Non-government company,Private,0.0,0.0,2013-04-11,"C/O SYANDAN PATRIKA , SAKUNTALA ROAD P.O - A...",Unlisted,Strike Off,tripura,India,72300.0,Business Services,4dbe5667-7b6b-41d7-82af-211562424d9a_f86d1f869...
3317878,3674312,U72900TR2020PTC013821,KNOWLEZZ GLOTECH PRIVATE LIMITED,ROC Guwahati,Company limited by shares,Non-government company,Private,1000000.0,100000.0,2020-08-25,"C/O Susanta Shome Jamtala Chandrapur,Agartal...",Unlisted,Active,tripura,India,72900.0,Business Services,4dbe5667-7b6b-41d7-82af-211562424d9a_f86d1f869...
3317879,3674313,U74999TR2018PTC013553,CLOUDNET DIGITAL INFONET PRIVATE LIMITED,ROC Guwahati,Company limited by shares,Non-government company,Private,100000.0,100000.0,2018-03-23,"AD NAGAR, ROAD NO-5, NEAR AD SCHOOL,,AGARTALA,...",Unlisted,Active,tripura,India,74999.0,Business Services,4dbe5667-7b6b-41d7-82af-211562424d9a_f86d1f869...
3317880,3674314,U88900TR2023NPL014331,BHABISHYAT JIBAN MICRO SERVICE FOUNDATION,ROC Guwahati,Company limited by shares,Non-government company,Private,1500000.0,300000.0,2023-12-27,"C/O SUJIT SARKAR,BRAJABINODINIPUR,Sidhai,West ...",Unlisted,Active,tripura,91,88900.0,"Community, personal and Social Services",4dbe5667-7b6b-41d7-82af-211562424d9a_f86d1f869...
3317881,3674315,U88900TR2025NPL014657,SAADHANBHOOMI FOUNDATION,ROC Guwahati,Company limited by shares,Non-government company,Private,1500000.0,50000.0,2025-09-18,"C/O RAIIB DEBNATH NEAR,LOKNATH BAZAR A.D. NAGA...",Unlisted,Active,tripura,91,88900.0,"Community, personal and Social Services",4dbe5667-7b6b-41d7-82af-211562424d9a_f86d1f869...